repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: detect-private-key
      - id: forbid-new-submodules
      - id: mixed-line-ending
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.15.0"
    hooks:
      - id: eslint
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.6.2"
    hooks:
      - id: prettier
        exclude: index.js|src
